-- Add many more scholarships to ensure comprehensive coverage (at least 3 per category)

INSERT INTO public.auto_scholarship_finder_2025_10_07_01_55 (
  scholarship_name, provider_organization, amount_min, amount_max, amount_type,
  eligibility_criteria, application_deadline, renewable, renewable_years,
  target_students, academic_requirements, geographic_restrictions, major_restrictions,
  application_requirements, website_url, contact_email
) VALUES

-- Additional National Scholarships
('Dell Scholars Program', 'Michael & Susan Dell Foundation', 20000, 20000, 'fixed',
 '{"financial_need": true, "academic_potential": true, "grit": true}',
 '2025-01-15', true, 4,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 2.4, "pell_eligible": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Online application', 'Essays', 'Recommendations', 'Financial documents'],
 'https://www.dellscholars.org', 'scholars@dellscholars.org'),

('Burger King Scholars Program', 'Burger King Foundation', 1000, 50000, 'range',
 '{"academic_excellence": true, "work_experience": true, "community_service": true}',
 '2024-12-15', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 2.5, "work_experience": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Online application', 'Essays', 'Work verification', 'Transcript'],
 'https://www.burgerkingfoundation.org', 'scholars@bkfoundation.org'),

('Foot Locker Scholar Athletes', 'Foot Locker Foundation', 20000, 20000, 'fixed',
 '{"athletic_participation": true, "academic_excellence": true, "leadership": true}',
 '2024-12-17', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.0, "athletic_participation": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Online application', 'Athletic verification', 'Essays', 'Recommendations'],
 'https://www.footlockerscholarathletes.com', 'scholars@footlocker.com'),

-- Additional State-Specific Scholarships - California
('California Dream Act Scholarship', 'California Student Aid Commission', 5000, 12570, 'range',
 '{"california_resident": true, "ab540_eligible": true, "financial_need": true}',
 '2025-03-02', true, 4,
 ARRAY['in_state'], 
 '{"gpa_min": 2.0, "california_resident": true, "undocumented_or_ab540": true}',
 ARRAY['California'], ARRAY['any'],
 ARRAY['California Dream Act Application', 'GPA verification', 'Financial documents'],
 'https://www.csac.ca.gov/dream-act', 'dreamact@csac.ca.gov'),

('Golden State Seal Merit Diploma Scholarship', 'California Department of Education', 2000, 2000, 'fixed',
 '{"california_resident": true, "seal_of_biliteracy": true, "academic_excellence": true}',
 '2025-04-01', false, 0,
 ARRAY['in_state'], 
 '{"gpa_min": 3.0, "california_resident": true, "bilingual": true}',
 ARRAY['California'], ARRAY['any'],
 ARRAY['School nomination', 'Seal verification', 'Transcript'],
 'https://www.cde.ca.gov', 'scholarships@cde.ca.gov'),

('California Teachers Association Scholarship', 'California Teachers Association', 5000, 5000, 'fixed',
 '{"california_resident": true, "education_major": true, "financial_need": true}',
 '2025-02-01', true, 4,
 ARRAY['in_state'], 
 '{"gpa_min": 3.5, "california_resident": true, "education_major": true}',
 ARRAY['California'], ARRAY['Education'],
 ARRAY['CTA application', 'Essays', 'Recommendations', 'Major verification'],
 'https://www.cta.org/scholarships', 'scholarships@cta.org'),

-- Additional State-Specific Scholarships - Texas
('Texas Public Educational Grant', 'Texas Higher Education Coordinating Board', 2000, 2000, 'fixed',
 '{"texas_resident": true, "financial_need": true, "public_institution": true}',
 '2025-03-15', true, 4,
 ARRAY['in_state'], 
 '{"gpa_min": 2.5, "texas_resident": true, "efc_max": 5000}',
 ARRAY['Texas'], ARRAY['any'],
 ARRAY['FAFSA', 'TASFA', 'Enrollment verification'],
 'https://www.thecb.state.tx.us', 'tpeg@thecb.state.tx.us'),

('Teach for Texas Scholarship', 'Texas Education Agency', 7500, 7500, 'fixed',
 '{"texas_resident": true, "education_major": true, "teaching_commitment": true}',
 '2025-04-01', true, 4,
 ARRAY['in_state'], 
 '{"gpa_min": 2.75, "texas_resident": true, "education_major": true}',
 ARRAY['Texas'], ARRAY['Education'],
 ARRAY['TEA application', 'Teaching commitment', 'University verification'],
 'https://tea.texas.gov/scholarships', 'scholarships@tea.texas.gov'),

('Texas Armed Services Scholarship', 'Texas Veterans Commission', 3000, 3000, 'fixed',
 '{"texas_resident": true, "military_family": true, "academic_merit": true}',
 '2025-05-01', true, 4,
 ARRAY['in_state'], 
 '{"gpa_min": 3.0, "texas_resident": true, "military_connection": true}',
 ARRAY['Texas'], ARRAY['any'],
 ARRAY['Military verification', 'Application', 'Transcript'],
 'https://www.tvc.texas.gov', 'scholarships@tvc.texas.gov'),

-- Additional State-Specific Scholarships - New York
('New York State Math and Science Teaching Incentive', 'New York State Education Department', 3400, 3400, 'fixed',
 '{"new_york_resident": true, "stem_education_major": true, "teaching_commitment": true}',
 '2025-05-01', true, 4,
 ARRAY['in_state'], 
 '{"gpa_min": 2.5, "new_york_resident": true, "stem_education": true}',
 ARRAY['New York'], ARRAY['Education', 'STEM'],
 ARRAY['NYSED application', 'Teaching commitment', 'Major verification'],
 'https://www.nysed.gov', 'scholarships@nysed.gov'),

('New York State Regents Award for Academic Excellence', 'New York State Education Department', 1500, 1500, 'fixed',
 '{"new_york_resident": true, "academic_excellence": true, "regents_diploma": true}',
 '2025-06-30', false, 0,
 ARRAY['in_state'], 
 '{"gpa_min": 90, "new_york_resident": true, "regents_diploma": true}',
 ARRAY['New York'], ARRAY['any'],
 ARRAY['School nomination', 'Regents scores', 'Transcript'],
 'https://www.nysed.gov', 'regents@nysed.gov'),

-- Additional First-Generation College Student Scholarships
('Coca-Cola First Generation Scholarship', 'Coca-Cola Scholars Foundation', 5000, 5000, 'fixed',
 '{"first_generation": true, "leadership": true, "community_service": true}',
 '2024-10-31', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.0, "first_generation": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Online application', 'Essays', 'Recommendations', 'First-gen verification'],
 'https://www.coca-colascholarsfoundation.org/first-gen', 'firstgen@coca-cola.com'),

('Sallie Mae Fund First in Family Scholarship', 'Sallie Mae Fund', 1000, 5000, 'range',
 '{"first_generation": true, "financial_need": true, "academic_potential": true}',
 '2025-01-31', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 2.5, "first_generation": true, "financial_need": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Online application', 'Essays', 'Financial documents', 'Family education history'],
 'https://www.salliemae.com/scholarships', 'scholarships@salliemae.com'),

('College Possible Scholarship', 'College Possible', 2000, 10000, 'range',
 '{"first_generation": true, "low_income": true, "program_participant": true}',
 '2025-03-01', true, 4,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 2.0, "first_generation": true, "program_participation": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Program application', 'Essays', 'Recommendations', 'Financial verification'],
 'https://www.collegepossible.org', 'scholarships@collegepossible.org'),

-- Additional Low-Income Student Scholarships
('United Way Scholarship', 'United Way Worldwide', 2500, 7500, 'range',
 '{"low_income": true, "community_service": true, "academic_merit": true}',
 '2025-02-15', true, 4,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 2.5, "family_income_max": 50000, "volunteer_hours_min": 50}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['United Way application', 'Service verification', 'Financial documents'],
 'https://www.unitedway.org/scholarships', 'scholarships@unitedway.org'),

('Walmart Foundation Scholarship', 'Walmart Foundation', 1000, 13000, 'range',
 '{"low_income": true, "academic_merit": true, "walmart_associate_family": true}',
 '2025-01-31', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 2.0, "walmart_connection": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Walmart application', 'Employment verification', 'Transcript'],
 'https://www.walmart.org/scholarships', 'scholarships@walmart.org'),

('Goodwill Scholarship Program', 'Goodwill Industries International', 2000, 10000, 'range',
 '{"low_income": true, "career_advancement": true, "goodwill_participant": true}',
 '2025-04-30', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 2.0, "goodwill_services": true, "career_goals": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Goodwill application', 'Service verification', 'Career plan'],
 'https://www.goodwill.org/scholarships', 'scholarships@goodwill.org'),

-- Additional International Student Scholarships
('International Education Financial Aid', 'Institute of International Education', 5000, 25000, 'range',
 '{"international_student": true, "academic_excellence": true, "financial_need": true}',
 '2025-01-15', true, 4,
 ARRAY['international'], 
 '{"gpa_min": 3.0, "english_proficiency": true, "financial_need": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['IIE application', 'Academic transcripts', 'Financial documents', 'English test'],
 'https://www.iie.org/scholarships', 'scholarships@iie.org'),

('Davis-Putter Scholarship Fund', 'Davis-Putter Scholarship Fund', 1000, 15000, 'range',
 '{"international_student": true, "social_activism": true, "academic_merit": true}',
 '2025-04-01', true, 4,
 ARRAY['international'], 
 '{"gpa_min": 2.0, "activism": true, "progressive_values": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Online application', 'Essays on activism', 'Recommendations', 'Transcript'],
 'https://www.davisputter.org', 'info@davisputter.org'),

('P.E.O. International Peace Scholarship', 'P.E.O. Sisterhood', 12500, 12500, 'fixed',
 '{"international_student": true, "women": true, "graduate_study": true}',
 '2024-12-15', false, 0,
 ARRAY['international'], 
 '{"gpa_min": 3.0, "women": true, "graduate_level": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['P.E.O. application', 'Academic records', 'Recommendations', 'Study plan'],
 'https://www.peointernational.org', 'ips@peodsm.org'),

-- Additional STEM Scholarships
('Google Lime Scholarship', 'Google and Lime Connect', 10000, 10000, 'fixed',
 '{"stem_field": true, "disability": true, "academic_excellence": true}',
 '2024-12-01', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.7, "stem_major": true, "disability": true}',
 ARRAY['national'], ARRAY['STEM'],
 ARRAY['Google application', 'Disability verification', 'Essays', 'Transcript'],
 'https://www.google.com/scholarships', 'scholarships@google.com'),

('Microsoft Scholarship Program', 'Microsoft Corporation', 5000, 5000, 'fixed',
 '{"stem_field": true, "underrepresented_minority": true, "academic_merit": true}',
 '2025-01-31', true, 4,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.0, "stem_major": true, "underrepresented": true}',
 ARRAY['national'], ARRAY['STEM'],
 ARRAY['Microsoft application', 'Essays', 'Recommendations', 'Portfolio'],
 'https://www.microsoft.com/scholarships', 'scholarships@microsoft.com'),

('Intel Science Talent Search', 'Society for Science', 7500, 250000, 'range',
 '{"stem_field": true, "research_project": true, "academic_excellence": true}',
 '2024-11-14', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.5, "stem_major": true, "research_experience": true}',
 ARRAY['national'], ARRAY['STEM'],
 ARRAY['Research project', 'Essays', 'Recommendations', 'Presentation'],
 'https://www.societyforscience.org/regeneron-sts', 'sts@societyforscience.org'),

-- Additional Minority Student Scholarships
('Thurgood Marshall College Fund', 'Thurgood Marshall College Fund', 3100, 16200, 'range',
 '{"african_american": true, "hbcu_student": true, "academic_merit": true}',
 '2025-01-15', true, 4,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.0, "african_american": true, "hbcu_enrollment": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['TMCF application', 'Essays', 'Recommendations', 'HBCU verification'],
 'https://www.tmcf.org', 'scholarships@tmcf.org'),

('American Indian College Fund', 'American Indian College Fund', 1000, 5000, 'range',
 '{"native_american": true, "tribal_membership": true, "academic_merit": true}',
 '2025-05-31', true, 4,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 2.0, "native_american": true, "tribal_verification": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['AICF application', 'Tribal enrollment', 'Essays', 'Recommendations'],
 'https://www.collegefund.org', 'scholarships@collegefund.org'),

('Asian Pacific Fund Scholarship', 'Asian Pacific Fund', 2500, 20000, 'range',
 '{"asian_pacific_islander": true, "financial_need": true, "community_service": true}',
 '2025-02-28', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.0, "asian_pacific_islander": true, "community_involvement": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['APF application', 'Essays', 'Service verification', 'Financial documents'],
 'https://www.asianpacificfund.org', 'scholarships@asianpacificfund.org'),

-- Additional Merit-Based Scholarships
('Siemens Competition', 'Siemens Foundation', 1000, 100000, 'range',
 '{"stem_field": true, "research_project": true, "academic_excellence": true}',
 '2024-10-01', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.5, "stem_research": true, "competition_entry": true}',
 ARRAY['national'], ARRAY['STEM'],
 ARRAY['Research project', 'Competition entry', 'Presentation', 'Peer review'],
 'https://www.siemens-foundation.org', 'foundation@siemens.com'),

('Davidson Fellows Scholarship', 'Davidson Institute', 10000, 50000, 'range',
 '{"exceptional_achievement": true, "significant_work": true, "under_18": true}',
 '2025-02-12', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"age_max": 18, "exceptional_work": true, "significant_contribution": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Portfolio submission', 'Project documentation', 'Recommendations', 'Interview'],
 'https://www.davidsongifted.org/fellows', 'fellows@davidsongifted.org'),

('Ayn Rand Institute Scholarships', 'Ayn Rand Institute', 500, 10000, 'range',
 '{"essay_competition": true, "academic_merit": true, "philosophical_interest": true}',
 '2025-04-26', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.0, "essay_writing": true, "objectivism_interest": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Essay submission', 'Academic transcript', 'Competition rules'],
 'https://www.aynrand.org/contests', 'essays@aynrand.org'),

-- Additional Community Service Scholarships
('Volunteer Generation Fund Scholarship', 'Points of Light', 1000, 5000, 'range',
 '{"community_service": true, "volunteer_leadership": true, "social_impact": true}',
 '2025-03-15', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"volunteer_hours_min": 100, "leadership_role": true, "community_impact": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Service portfolio', 'Impact documentation', 'Leadership examples', 'Recommendations'],
 'https://www.pointsoflight.org', 'scholarships@pointsoflight.org'),

('Kiwanis Club Scholarship', 'Kiwanis International', 1000, 2500, 'range',
 '{"community_service": true, "leadership": true, "kiwanis_connection": true}',
 '2025-02-01', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.0, "community_service": true, "kiwanis_involvement": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Kiwanis application', 'Service verification', 'Club recommendation'],
 'https://www.kiwanis.org/scholarships', 'scholarships@kiwanis.org'),

('Rotary Foundation Scholarship', 'Rotary International', 2500, 30000, 'range',
 '{"community_service": true, "international_understanding": true, "leadership": true}',
 '2025-05-15', true, 2,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.0, "community_service": true, "rotary_connection": true}',
 ARRAY['national'], ARRAY['any'],
 ARRAY['Rotary application', 'Service portfolio', 'Club sponsorship', 'Interview'],
 'https://www.rotary.org/scholarships', 'scholarships@rotary.org'),

-- Additional Women in STEM Scholarships
('Adobe Research Women-in-Technology Scholarship', 'Adobe Inc.', 10000, 10000, 'fixed',
 '{"women": true, "technology": true, "academic_excellence": true}',
 '2024-11-15', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.0, "women": true, "technology_major": true}',
 ARRAY['national'], ARRAY['Technology'],
 ARRAY['Adobe application', 'Portfolio', 'Essays', 'Recommendations'],
 'https://www.adobe.com/scholarships', 'scholarships@adobe.com'),

('Palantir Women in Technology Scholarship', 'Palantir Technologies', 7000, 7000, 'fixed',
 '{"women": true, "computer_science": true, "underrepresented": true}',
 '2024-12-01', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.0, "women": true, "cs_major": true}',
 ARRAY['national'], ARRAY['Computer Science'],
 ARRAY['Palantir application', 'Technical portfolio', 'Essays', 'Coding challenge'],
 'https://www.palantir.com/scholarships', 'scholarships@palantir.com'),

('Anita Borg Memorial Scholarship', 'Google', 10000, 10000, 'fixed',
 '{"women": true, "computer_science": true, "leadership": true}',
 '2024-12-01', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.5, "women": true, "cs_major": true, "leadership": true}',
 ARRAY['national'], ARRAY['Computer Science'],
 ARRAY['Google application', 'Essays', 'Leadership examples', 'Technical projects'],
 'https://www.google.com/scholarships/anita-borg', 'anitaborg@google.com'),

-- Additional Arts and Creative Scholarships
('Scholastic Art & Writing Awards', 'Scholastic Inc.', 500, 10000, 'range',
 '{"creative_arts": true, "portfolio_submission": true, "artistic_excellence": true}',
 '2025-01-10', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"artistic_merit": true, "portfolio_quality": true, "creative_expression": true}',
 ARRAY['national'], ARRAY['Art', 'Creative Writing', 'Design'],
 ARRAY['Portfolio submission', 'Artist statement', 'Competition entry'],
 'https://www.artandwriting.org', 'info@artandwriting.org'),

('National YoungArts Foundation', 'YoungArts Foundation', 100, 10000, 'range',
 '{"performing_arts": true, "visual_arts": true, "artistic_excellence": true}',
 '2024-10-15', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"age_max": 18, "artistic_talent": true, "portfolio_submission": true}',
 ARRAY['national'], ARRAY['Art', 'Music', 'Theater', 'Dance', 'Film'],
 ARRAY['Audition/Portfolio', 'Application', 'Artistic samples'],
 'https://www.youngarts.org', 'info@youngarts.org'),

('Princess Grace Foundation Scholarship', 'Princess Grace Foundation', 5000, 25000, 'range',
 '{"performing_arts": true, "theater": true, "dance": true}',
 '2025-03-31', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.0, "performing_arts": true, "professional_training": true}',
 ARRAY['national'], ARRAY['Theater', 'Dance', 'Film'],
 ARRAY['Audition', 'Portfolio', 'Recommendations', 'Training verification'],
 'https://www.pgfusa.org', 'grants@pgfusa.org'),

-- Additional Business and Entrepreneurship Scholarships
('DECA Scholarship Program', 'DECA Inc.', 1000, 5000, 'range',
 '{"business_interest": true, "deca_member": true, "leadership": true}',
 '2025-01-15', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.0, "deca_membership": true, "business_major": true}',
 ARRAY['national'], ARRAY['Business', 'Marketing', 'Finance'],
 ARRAY['DECA application', 'Membership verification', 'Business plan', 'Essays'],
 'https://www.deca.org/scholarships', 'scholarships@deca.org'),

('Future Business Leaders of America Scholarship', 'FBLA-PBL', 1000, 12500, 'range',
 '{"business_leadership": true, "fbla_member": true, "academic_merit": true}',
 '2025-03-01', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 3.0, "fbla_membership": true, "leadership_role": true}',
 ARRAY['national'], ARRAY['Business'],
 ARRAY['FBLA application', 'Leadership portfolio', 'Competition results', 'Essays'],
 'https://www.fbla-pbl.org/scholarships', 'scholarships@fbla-pbl.org'),

('Network for Teaching Entrepreneurship Scholarship', 'NFTE', 2000, 10000, 'range',
 '{"entrepreneurship": true, "business_plan": true, "innovation": true}',
 '2025-04-15', false, 0,
 ARRAY['in_state', 'out_of_state'], 
 '{"gpa_min": 2.5, "entrepreneurial_spirit": true, "business_idea": true}',
 ARRAY['national'], ARRAY['Business', 'Entrepreneurship'],
 ARRAY['Business plan', 'Pitch presentation', 'Essays', 'Financial projections'],
 'https://www.nfte.com/scholarships', 'scholarships@nfte.com');

-- Create additional indexes for better performance
CREATE INDEX IF NOT EXISTS idx_auto_scholarships_target_students ON public.auto_scholarship_finder_2025_10_07_01_55 USING GIN(target_students);
CREATE INDEX IF NOT EXISTS idx_auto_scholarships_major_restrictions ON public.auto_scholarship_finder_2025_10_07_01_55 USING GIN(major_restrictions);
CREATE INDEX IF NOT EXISTS idx_auto_scholarships_renewable ON public.auto_scholarship_finder_2025_10_07_01_55(renewable);
CREATE INDEX IF NOT EXISTS idx_auto_scholarships_provider ON public.auto_scholarship_finder_2025_10_07_01_55(provider_organization);