name: Daily Scholarship Ingestion

on:
  schedule:
    - cron: '0 3 * * *'   # daily at 03:00 UTC
  workflow_dispatch: {}   # allow manual trigger

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run scholarship ingestion
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        run: node ingest-sources.js
        
      - name: Upload ingestion logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ingestion-logs
          path: |
            *.log
            ingestion-report.json
          retention-days: 30